### ISSUE TITLE
Option to run only on save

### ISSUE THREAD

**Issue by dylan-chong** [thirtythreeforty/lessspace.vim#11]
It is a bit less intrusive/surprising that way. I'm not sure this possible based on how the plug in is permitted. If not possible, it's not a big deal

**Comment by thirtythreeforty** [comment]
Currently this would be a very intrusive change to make, because LessSpace only tracks the current change being made.  Stripping when saving would require keeping track of _all_ changed lines, which is much more difficult, especially as lines are inserted or removed.

You might be interested in https://github.com/tweekmonster/wstrip.vim, which uses `diff` or `git-diff` to check the file against the one on the disk to find the lines to strip.

I would welcome help on this, but unfortunately I don't think I am going to be able to tackle it myself.  Feel free to reopen if you're interested.
