### ISSUE TITLE
Breaks a common reverse spell-checking mapping.

### ISSUE THREAD

**Issue by bennyty** [thirtythreeforty/lessspace.vim#5]
Thank you for making this plugin, it's almost everything I'm looking for. Unfortunately for me it frequently messes up a mapping for auto-correcting the last spelling mistake before the cursor.
```
inoremap <c-f> <c-g>u<Esc>[s1z=`]a<c-g>u
nnoremap <c-f> [s1z=<c-o>
```
If I tpyed this sentence wrong. And hit `<c-f>` right here|
Then the sentence would be corrected and the cursor would jump back to the correct spot. Everything is dandy.

However if I typed TIHS sentence wrong. And hit `<c-f>` right here   | (notice the space)
Then I think the `] mark gets overwritten and the cursor ends up after the first character of the line.

Any suggestions?

**Comment by thirtythreeforty** [comment]
I understand the normal mapping; it just jumps back to the last error, corrects it, and moves back.  LessSpace is going to modify the line after the `nnoremap` executes, but it will have already been modified when you left insert mode to execute this mapping in the first place, so I don't see much issue there.

Now, as I understand it, the inoremap saves undo state, leaves insert mode, jumps to the last error, corrects it, jumps back, and reenters insert mode.  When you use the insert mode mapping, you're leaving insert mode temporarily, so LessSpace autocommands will run.  You are correct; the `']` mark is being modified.

I can save the `'[` and `']` marks before modifying the buffer (and arguably should do that anyway), but your extra space in your second example is going to get deleted because you're leaving insert mode in your autocommand.  Does that sound good?

**Comment by bennyty** [comment]
Sounds perfect. You're right I shouldn't have left the normal mode mapping in, it's unaffected. And it's find that the space gets deleted, the only thing the matters for my use case is that the cursor's position is unaffected or only minorly affected. The goal of those mappings was to correct the last error and not move the cursor so you could continue typing without interruption so it's jarring when `']` gets deleted and the cursor ends up at the beginning of the line. I don't mind reinserting a space. 

Ofc, I could also just modify the mapping so that it drops a mark and jumps back to it but a solution that restores `']` would be ideal for other people who then won't have to deal with the unintuitive behavior.

**Comment by thirtythreeforty** [comment]
OK then, that's what I'll do.

Related: I've looked around Vim for a way to detect that a mapping is running, so LessSpace could not do anything then.  This would prevent the slight cursor motion when the space is removed.  Unfortunately I can't find a way (any guidance would be appreciated!), so this behavior is as good as it can get for now.

**Comment by bennyty** [comment]
That is legitimately the fastest I've ever seen an issue be patched and closed. Well done.
